image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run App
    init: npm install
    command: npm run start:watch

  - name: Test
    init: npm install
    command: npm run test:watch

  - name: Console
    command: gp await-port 3000 && sleep 3 && gp preview $(gp url 3000)/

ports:
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
